sudo: false

language: java
jdk: openjdk11

before_install:
- unset _JAVA_OPTIONS

script:
- mvn -Prun-its verify

after_success:
- tail -200 target/it/multiple-engines/build.log

after_failure:
- tail -200 target/it/configured/build.log
- tail -200 target/it/jupiter-5.4.0-platform-1.4.0-SNAPSHOT/build.log
- tail -200 target/it/modular-world-1-main-plain-test-module/build.log
- tail -200 target/it/modular-world-2-main-module-test-plain/build.log
- tail -200 target/it/multiple-engines/build.log
- tail -200 target/it/timeout/build.log

cache:
  directories:
  - $HOME/.m2
